### ISSUE TITLE
ansible lunar ppa deb has weird plugins/modules/snap.py version that doesn't work (at least on mantic)

### ISSUE THREAD

**Issue by jikamens** [ansible-community/ppa#59]
The file /usr/lib/python3/dist-packages/ansible_collections/community/general/plugins/modules/snap.py in the ppa deb for lunar doesn't match the file plugins/modules/snap.py in the community.general repository. I can't figure out where the version of snap.py in the deb came from; it doesn't even seem to match any historical version of plugins/modules/snap.py in the community.general repository, at first glance.

It also doesn't work, at least not on Mantic. This task:

```
  - snap:
      name:
      - vault
      - bw
      - chromium
```

Produces this output when ansible-playbook is run with -vvv:

```
TASK [snap] ********************************************************************
task path: /home/jik/src/family-orchestration/desktops/install_packages.yml:849
redirecting (type: modules) ansible.builtin.snap to community.general.snap
redirecting (type: modules) ansible.builtin.snap to community.general.snap
Using module file /usr/lib/python3/dist-packages/ansible_collections/community/general/plugins/modules/snap.py
Pipelining is enabled.
<jik5.kamens.us> ESTABLISH SSH CONNECTION FOR USER: root
<jik5.kamens.us> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/jik/.ansible/cp/1d985d2fdd"' jik5.kamens.us '/bin/sh -c '"'"'/usr/bin/python3 && sleep 0'"'"''
<jik5.kamens.us> (1, b'\n{"exception": "Traceback (most recent call last):\\n  File \\"/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/module_utils/mh/deco.py\\", line 52, in wrapper\\n    func(self, *args, **kwargs)\\n  File \\"/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/module_utils/mh/base.py\\", line 79, in run\\n    self.__init_module__()\\n  File \\"/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/modules/snap.py\\", line 214, in __init_module__\\n  File \\"/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/modules/snap.py\\", line 328, in names_from_snaps\\n  File \\"/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/module_utils/cmd_runner.py\\", line 290, in run\\n    self.results_processed = self.output_process(*results)\\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\"/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/modules/snap.py\\", line 324, in process\\n  File \\"/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/modules/snap.py\\", line 309, in process_many\\n  File \\"/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/modules/snap.py\\", line 302, in process_one\\nIndexError: list index out of range\\n", "output": {}, "vars": {}, "failed": true, "msg": "Module failed with exception: list index out of range", "invocation": {"module_args": {"name": ["vault", "bw", "chromium"], "state": "present", "classic": false, "dangerous": false, "channel": null, "options": null}}}\n', b'')
<jik5.kamens.us> Failed to connect to the host via ssh: 
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/module_utils/mh/deco.py", line 52, in wrapper
    func(self, *args, **kwargs)
  File "/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/module_utils/mh/base.py", line 79, in run
    self.__init_module__()
  File "/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/modules/snap.py", line 214, in __init_module__
  File "/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/modules/snap.py", line 328, in names_from_snaps
  File "/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/module_utils/cmd_runner.py", line 290, in run
    self.results_processed = self.output_process(*results)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/modules/snap.py", line 324, in process
  File "/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/modules/snap.py", line 309, in process_many
  File "/tmp/ansible_snap_payload_gtxruhk4/ansible_snap_payload.zip/ansible_collections/community/general/plugins/modules/snap.py", line 302, in process_one
IndexError: list index out of range
fatal: [jik5.kamens.us]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "channel": null,
            "classic": false,
            "dangerous": false,
            "name": [
                "vault",
                "bw",
                "chromium"
            ],
            "options": null,
            "state": "present"
        }
    },
    "msg": "Module failed with exception: list index out of range",
    "output": {},
    "vars": {}
}
```

When I use the version of snap.py in community.general everything is fine.

Why is there an old, broken version of this module in the deb?

**Comment by jikamens** [comment]
Hmm. The modules nmcli.py and dconf.py are also different (and presumably out-of-date) in the deb. I'm really confused about what's going on here.

**Comment by dericcrago** [comment]
Hi @jikamens - I think it's something with your environment, `ansible_collections/community/general/plugins/modules/snap.py` in `8.2.0` looks like a match to me:

```
# mkdir {deb,tar}
# curl -L https://launchpad.net/~ansible/+archive/ubuntu/ansible/+files/ansible_8.2.0-1ppa~lunar_all.deb --silent --output ansible_8.2.0-1ppa~lunar_all.deb
# dpkg-deb -x ansible_8.2.0-1ppa~lunar_all.deb deb
# curl -L https://files.pythonhosted.org/packages/dd/8d/cb83551686b964377110e215740a75dca253100ef57d4b11f65613c83e13/ansible-8.2.0.tar.gz --silent --output ansible-8.2.0.tar.gz
# tar -xzf ansible-8.2.0.tar.gz -C tar
# sha1sum ./deb/usr/lib/python3/dist-packages/ansible_collections/community/general/plugins/modules/snap.py
b8636400e4a783d2e55df34d1fd2ff23313b3d4f  ./deb/usr/lib/python3/dist-packages/ansible_collections/community/general/plugins/modules/snap.py
# sha1sum ./tar/ansible-8.2.0/ansible_collections/community/general/plugins/modules/snap.py
b8636400e4a783d2e55df34d1fd2ff23313b3d4f  ./tar/ansible-8.2.0/ansible_collections/community/general/plugins/modules/snap.py
```

**Comment by jikamens** [comment]
It's not something in my environment.

You're looking at the files in the ansible release on PyPI. I'm looking at the files in the community.general Github repository. The files in the ansible 8.2.0 release on PyPI do match what's in the lunar deb, but they are very out-of-date with respect to what's in the community.general Github repository. I guess that means I need to take this up with the people who build ansible releases rather than with you?

I'm just quite confused about why the files shipped in the ansible PyPI release would not be the current community.general release. And they're not just not the current community.general release; they're _very_ out-of-date.

**Comment by dericcrago** [comment]
Looks like the same file that is in the latest `community.general` release to me 🤷 

```
# git clone https://github.com/ansible-collections/community.general.git
Cloning into 'community.general'...
remote: Enumerating objects: 66318, done.
remote: Counting objects: 100% (2299/2299), done.
remote: Compressing objects: 100% (980/980), done.
remote: Total 66318 (delta 1525), reused 1986 (delta 1301), pack-reused 64019
Receiving objects: 100% (66318/66318), 25.12 MiB | 15.49 MiB/s, done.
Resolving deltas: 100% (43892/43892), done.
# cd community.general/
# git checkout tags/7.2.0
Note: switching to 'tags/7.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at b02ea33f9 Release 7.2.0.
# sha1sum plugins/modules/snap.py
b8636400e4a783d2e55df34d1fd2ff23313b3d4f  plugins/modules/snap.py
```

**Comment by jikamens** [comment]
OK, found the bug and fixed it and submitted a PR:

https://github.com/ansible-collections/community.general/pull/7046

Sorry again for bugging you.
