### ISSUE TITLE
GitHub Actions 504 Gateway Timeout (apt-add-repository)

### ISSUE THREAD

**Issue by austin-shadow** [ansible-community/ppa#86]
My GitHub action had been working perfectly up until tonight. No changes were made, but I am getting a `504 Gateway Timeout` error during the `sudo apt-add-repository ppa:ansible/ansible -y` step.

```
Run sudo apt-add-repository ppa:ansible/ansible -y
  sudo apt-add-repository ppa:ansible/ansible -y
  sudo apt update
  sudo apt install ansible
  

Repository: 'deb https://ppa.launchpadcontent.net/ansible/ansible/ubuntu/ jammy main'
Description:
Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy. Avoid writing scripts or custom code to deploy and update your applications— automate in a language that approaches plain English, using SSH, with no agents to install on remote systems.
http://ansible.com/
If you face any issues while installing Ansible PPA, file an issue here:
https://github.com/ansible-community/ppa/issues
More info: https://launchpad.net/~ansible/+archive/ubuntu/ansible
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/ansible-ubuntu-ansible-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/ansible-ubuntu-ansible-jammy.list
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 364, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
  File "/usr/bin/apt-add-repository", line 357, in main
    shortcut.add()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 222, in add
    self.add_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 398, in add_key
    if not all((self.trustedparts_file, self.trustedparts_content)):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 141, in trustedparts_content
    key = self.lpppa.getSigningKeyData()
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 592, in __call__
    response, content = self.root._browser._request(
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 429, in _request
    raise error
lazr.restfulclient.errors.ServerError: HTTP Error 504: Gateway Time-out
Response headers:
---
-content-encoding: gzip
cache-control: no-cache
content-length: 92
content-type: text/html
date: Sat, 06 Apr 2024 01:53:38 GMT
server: Apache/2.4.41 (Ubuntu)
status: 504
vary: Accept-Encoding
---
Response body:
---
b"<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n"
---
Error: Process completed with exit code 1.
```

**Comment by austin-shadow** [comment]
Well, the good news is the issue self-solved. If anyone else runs into this situation, just wait it out a bit.
